gvc/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('customer/login_customer/', views.login_view, name='login'),  
    path('staff/login_staff/', views.admin_view, name='login_staff'),
    path('customer/logout/', views.logout_view, name='customer_logout'),
    path('staff/logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    
]

gvc/api/urls.py
from django.urls import path
from .views import property_type_list

app_name = 'api'

urlpatterns=[
    path('', property_type_list, name='api'),
]

gvc/core/urls.py
from django.urls import path
from .views import index,  submit_reading


app_name='core'


urlpatterns = [
    path('', index, name='index'),
    path('submit_reading/', submit_reading, name='submit_reading'),
    
    
]

gvc/gvc/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('',include('core.urls',namespace='core')),
    path('api/',include('api.urls',namespace='api')),
    path('Admin_panel/',include('Admin_panel.urls',namespace='Admin_panel')),
]

gvc/frontend/templates/Admin.html
{%  extends 'base.html' %}
    <div class="container">
      <h1 class="text-center">Welcome to the <i class="fa-solid fa-bolt"></i>iGSE Admin Dashboard</h1>
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="card">
    <div class="card-body">
        <h5 class="card-title">Set Prices</h5>
        <form>
        <div class="form-group">
            <label for="electricityDayPrice">Electricity (Day) Price</label>
            <input type="number" class="form-control" id="electricityDayPrice" value="0.15">
        </div>
        <div class="form-group">
            <label for="electricityNightPrice">Electricity (Night) Price</label>
            <input type="number" class="form-control" id="electricityNightPrice" value="0.10">
        </div>
        <div class="form-group">
            <label for="gasPrice">Gas Price</label>
            <input type="number" class="form-control" id="gasPrice" value="0.12">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
    </div>
    </div>
    <div class="col-sm-12 col-md-8">
    <div class="card">
    <div class="card-body">
        <h5 class="card-title">View Meter Readings</h5>
        <table class="table">
        <thead>
            <tr>
            <th>Customer ID</th>
            <th>Submission Date</th>
            <th>Electricity (Day)</th>
            <th>Electricity (Night)</th>
            <th>Gas</th>
            </tr>
        </thead>
        <tbody>
            <tr>
            <td>customer1@email.com</td>
            <td>2022-11-05</td>
            <td>100</td>
            <td>250</td>
            <td>800</td>
            </tr>
            <tr>
            <td>customer2@email.com</td>
            <td>2022-11-07</td>
            <td>120</td>
            <td>280</td>
            <td>850</td>
            </tr>
        </tbody>
        </table>
    </div>
    </div>
    </div>
    <div class="col-sm-12 col-md-12">
    <div class="card">
        <div class="card-body">
        <h5 class="card-title">View Energy Statistics</h5>
        <p><i class="fa-solid fa-bolt"></i>Average electricity (day) consumption: 110 kWh</p>
        <p><i class="fa-solid fa-bolt"></i>Average electricity (night) consumption: 265 kWh</p>
        <p><i class="fa-solid fa-bolt"></i>Average gas consumption: 825 kWh</p>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

gvc/frontend/templates/Registration.html
{% extends 'base.html'  %}
    <div class="container">
      <h1 class="text-center"><i class="fa-solid fa-bolt"></i>iGSE - Customer Registration</h1>
      <form>
        <div class="form-group">
          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" placeholder="Password">
        </div>
        <div class="form-group">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" placeholder="Enter your address">
        </div>
        <div class="form-group">
          <label for="propertyType">Property Type</label>
          <select class="form-control" id="propertyType">
            <option>Detached</option>
            <option>Semi-detached</option>
            <option>Terraced</option>
            <option>Flat</option>
            <option>Cottage</option>
            <option>Bungalow</option>
            <option>Mansion</option>
          </select>
        </div>
        <div class="form-group">
          <label for="bedrooms">Number of Bedrooms</label>
          <input type="number" class="form-control" id="bedrooms" placeholder="Enter number of bedrooms">
        </div>
        <div class="form-group">
          <label for="evc">Energy Voucher Code</label>
          <input type="text" class="form-control" id="evc" placeholder="Enter 8-digit EVC">
        </div>
        <div class="form-group">
          <label for="qr-code">Or</label>
          <input type="file" class="form-control-file" id="qr-code">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <p>Already Have an account?<a href="login.html">Login</a></p>
      </form>
    </div>
  {%  endblock %}

gvc/frontend/templates/admin.html
{%  extends 'base.html' %}

{% block content %}
    <div class="container">
              <!-- Logout -->
    <h3 class="text-center"><a href="{% url 'accounts:logout' %}" class="btn btn-primary">Logout</a></h3>
                
      <h1 class="text-center">Welcome to the <i class="fa-solid fa-bolt"></i>iGSE Admin Dashboard</h1>

      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="card">
    <div class="card-body">
        <h5 class="card-title">Set Prices</h5>
        <form>
        <div class="form-group">
            <label for="electricityDayPrice">Electricity (Day) Price</label>
            <input type="number" class="form-control" id="electricityDayPrice" value="0.15">
        </div>
        <div class="form-group">
            <label for="electricityNightPrice">Electricity (Night) Price</label>
            <input type="number" class="form-control" id="electricityNightPrice" value="0.10">
        </div>
        <div class="form-group">
            <label for="gasPrice">Gas Price</label>
            <input type="number" class="form-control" id="gasPrice" value="0.12">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
    </div>
    </div>
    <div class="col-sm-12 col-md-8">
    <div class="card">
    <div class="card-body">
        <h5 class="card-title">View Meter Readings</h5>
        <table class="table">
        <thead>
            <tr>
            <th>Customer ID</th>
            <th>Submission Date</th>
            <th>Electricity (Day)</th>
            <th>Electricity (Night)</th>
            <th>Gas</th>
            </tr>
        </thead>
        <tbody>
            {%  for meters in  meter %}
            <tr>
            <td>{{meters.customer}}</td>
            <td>{{meters.submission_date}}</td>
            <td>{{meters.electricity_day}}</td>
            <td>{{meters.electricity_night}}</td>
            <td>{{meters.gas}}</td>
            </tr>
           {% endfor %}
        </tbody>
        </table>
    </div>
    </div>
    </div>
    <div class="col-sm-12 col-md-12">
    <div class="card">
        <div class="card-body">
        <h5 class="card-title">View Energy Statistics</h5>
        
        <p><i class="fa-solid fa-bolt"></i>Average electricity (day) consumption: {{avarage_day.day_avg}} kWh</p>
        <p><i class="fa-solid fa-bolt"></i>Average electricity (night) consumption: {{electricity_night}} kWh</p>
        <p><i class="fa-solid fa-bolt"></i>Average gas consumption: {{gas}}kWh</p>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

gvc/frontend/templates/admin_login.html
{% extends 'base.html' %}

{% block content %}
      
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title text-center"><span class="badge bg-success">Admin Login</span></h5>
              <form method='POST' action="{% url 'accounts:login_staff' %}">
                {% csrf_token %}
                 {{form.non_field_errors}}
                <div class="form-group">
                  <label for="email">Email</label>
                  {{form.email}}
                  <small class="text-danger">{{form.email.errors}}</small>
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  {{form.password}}
                  <small class="text-danger">{{form.password.errors}}</small>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

gvc/frontend/templates/base.html

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>iGSE - Customer Dashboard</title>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{%  url 'accounts:login' %}"><div class="col" ><img  height="70"src="{% static 'images\logo.png' %}"> </div></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
            


          </li>
         
          <li><a class="nav-link" href="{% url 'accounts:login_staff'  %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'accounts:login' %}">Customer</a></li>

          
        </ul>
      </div>
    
    </nav>


    {% block content %}

    {% endblock %}

</body>
</html>

gvc/frontend/templates/index.html

{% extends 'base.html'   %}
{% block content %}
      <div class="container alignt-items end"> <span class="btn-danger"><a href="{% url 'accounts:logout'%}">Logout</a></span></div>

      <div class="col"><h1 class="text-center text-white p-3 mb-2 bg-primary">Welcome To Your <i class="fa-solid fa-bolt"></i>iGSE Dashboard!</h1></div>
      
<div class="container"> 
    <div class="row">
        <div class="col">
            <!-- <div class="col-sm-12 col-md-6"> -->
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Submit Meter Reading</h5>
                <form action="{% url 'core:submit_reading' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="submissionDate">Submission Date</label>
                    {{ reading_form.submission_date }}
                    {{ reading_form.submission_date.errors }}
                    <small class="text-info">{{ reading_form.submission_date.help_text }}</small>
                    

                  </div>
                  <div class="form-group">
                    <label for="electricityDay">Electricity Meter Reading (Day)</label>
                    {{ reading_form.electricity_day }}
                    {{ reading_form.electricity_day.errors }}
                    <small class="text-info">{{ reading_form.electricity_day.help_text }}</small>
                  </div>
                  <div class="form-group">
                    <label for="electricityNight">Electricity Meter Reading (Night)</label>
                    {{ reading_form.electricity_night }}
                    {{ reading_form.electricity_night.errors }}
                    <small class="text-info">{{ reading_form.electricity_night.help_text }}</small>
                  </div>
                  <div class="form-group">
                    <label for="gas">Gas Meter Reading</label>
                    {{ reading_form.gas }}
                    {{ reading_form.gas.errors }}
                    <small class="text-info">{{ reading_form.gas.help_text }}</small>
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
              </div>
            </div>
          </div>
        
        <div class="col">
        <div class="col">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title">Your Usage</h5>
                <!-- Adding Bill here -->
                <h2>Latest Bill</h2>
                <p class="card-text">View and pay your latest energy bill using your energy credit.</p>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Bill Date</th>
                        <th scope="col">Bill Amount</th>
                        <th scope="col">Settled</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bill in bills %}
                    <tr>
                       
                        <td>{{ bill.bill_date | date:"d/m/Y" }}</td>
                        <td>£{{ bill.amount }}</td>
                        
                        {% if bill.paid %}
                          <td>Paid</td>
                        {% else %}
                          <td>Not Paid</td>
                          
                        {% endif %}
                          
                       
                        
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <a href="#" class="btn btn-primary">Pay Bill</a>
               
            </div>
        <div class="container">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Credit</h5>
                <h4 class="badge bg-secondary">Your Available Credit:<span class="badge bg-success">400 EUR</span></h4>
                <p class="card-text">Top up your energy credit using a valid Energy Voucher Code (EVC).</p>
                
                <div class="mb-3"  > <input type="text" class="form-control" placeholder="Enter your EVC"></div>
                <a href="#" class="btn btn-primary">Top Up</a>
              </div>
            </div>
          </div>
        </div>
        </div>
        </div>
        <div>

</div>
        </div>

  {%  endblock content %}

gvc/frontend/templates/login.html
{% extends 'base.html' %}

{% block content %}
      
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title text-center"><span class="badge bg-success">Customer Login</span></h5>
              <form method='POST' action="{% url 'accounts:login' %}">
                {% csrf_token %}
                 {{form.non_field_errors}}
                <div class="form-group">
                  <label for="email">Email</label>
                  {{form.email}}
                  <small class="text-danger">{{form.email.errors}}</small>
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  {{form.password}}
                  <small class="text-danger">{{form.password.errors}}</small>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Login</button>
              </form>
              <a class="text-center" href="{% url 'accounts:register' %}">Register</a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

gvc/frontend/templates/payment.html
{%  extends 'base.html' %}


{%  block content %}

{%  include 'includes/bill.html' %}
<h1>Make Payment</h1>
<form method="post">
    {% csrf_token %}
    <label for="amount">Amount:</label>
    <input type="text" name="amount" id="amount" required>
    <input type="submit" value="Make Payment">
</form>


{%  endblock %}

gvc/frontend/templates/register.html
{% extends 'base.html'  %}
  {% block title %}iGSE - Customer Registration{% endblock %}
  {% block content %}
    <div class="container">
      <h1 class="text-center"><i class="fa-solid fa-bolt"></i>iGSE - Customer Registration</h1>
      <form method="post" action="{% url 'accounts:register' %}" enctype="multipart/form-data">  {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
          <label for="email">Email address</label>
          {{ form.email  }}
          {{ form.email.errors  }}
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          {{ form.password  }}
          {{ form.password.errors  }}
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          {{ form.repeat_password  }}
          {{ form.repeat_password.errors  }}
        </div>
        <div class="form-group">
          <label for="address">Address</label>
          {{ form.address  }}
          {{ form.address.errors  }}
        </div>
        <div class="form-group">
          <label for="propertyType">Property Type</label>
          {{ form.property_type  }}
          {{ form.property_type.errors  }}
        </div>
        <div class="form-group">
          <label for="bedrooms">Number of Bedrooms</label>
          {{ form.number_of_bedrooms  }}
          {{ form.number_of_bedrooms.errors  }}
        </div>
        <div class="form-group">
          <label for="evc">Energy Voucher Code</label>
          {{ form.voucher_code  }}
          {{ form.voucher_code.errors  }}
        </div>
        <div class="form-group">
          <label for="qr-code">Or</label>
          <input type="file" class="form-control-file" id="qr-code">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <p>Already Have an account?<a href="{%  url 'accounts:login' %}">Login</a></p>
      </form>
    </div>
  {%  endblock %}